---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cust0-pvc-operator
subjects:
- kind: ServiceAccount
  name: cust0-pvc-operator
  namespace: cdi
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

